### ISSUE TITLE
I cannot access to the file EmotiW_VGG_S.caffemodel

### ISSUE THREAD

**Issue by qqqafter** [lacouth/cpp_emotions_detector#1]
Hi, I'm trying to run your code, but I can't because I can't download the model. There is some way to access it (I mean the EmotiW_VGG_S.caffemodel model)?

**Comment by lacouth** [comment]
Hi, the link in the README still works for me; here is the link again: https://drive.google.com/file/d/0BydFau0VP3XSNVYtWnNPMU1TOGM/view?resourcekey=0-XCp7bVfEV4ZBnCPaZcCjKA.

Remember, you have to follow all the steps in the README to get the application working. I'm closing the issue, but let me know if you have any problems.

**Comment by qqqafter** [comment]
Thank you, link work fine for me, i don't know why it don't worked earlier. The app works fine .
